ALTER TABLE dim_users
    ALTER COLUMN first_name TYPE VARCHAR(255),
    ALTER COLUMN last_name TYPE VARCHAR(255),
    ALTER COLUMN date_of_birth TYPE DATE,
    ALTER COLUMN company TYPE VARCHAR(255),
    ALTER COLUMN email_address TYPE VARCHAR(255),
    ALTER COLUMN address TYPE VARCHAR(255),
    ALTER COLUMN country TYPE VARCHAR(255),
    ALTER COLUMN country_code TYPE VARCHAR(3),
    ALTER COLUMN user_uuid TYPE UUID USING user_uuid::UUID,
    ALTER COLUMN join_date TYPE DATE;